import { Routes } from '@angular/router';
import { PatternMatchingComponent } from './features/pattern-matching/pattern-matching.component';
import { OddDirectionComponent } from './features/odd-direction/odd-direction.component';
import { ShadeSortingComponent } from './features/shade-sorting/shade-sorting.component';
import { NumberSequenceComponent } from './features/number-sequence/number-sequence.component';
import { SymbolMatchingComponent } from './features/symbol-matching/symbol-matching.component';
import { MultiConditionSelectionComponent } from './features/multi-condition-selection/multi-condition-selection.component';
import { AnimalPositionComponent } from './features/animal-position/animal-position.component';
import { PatternMatchingTwoComponent } from './features/pattern-matching-two/pattern-matching-two.component';
import { ShapeColoringComponent } from './features/shape-coloring/shape-coloring.component';
import { LiquidSelectionComponent } from './features/liquid-selection/liquid-selection.component';
import { LongestRopeComponent } from './features/longest-rope/longest-rope.component';
import { LetterMatchingComponent } from './features/letter-matching/letter-matching.component';
import { ShapePatternComponent } from './features/shape-pattern/shape-pattern.component';
import { BoardLetterMatchingComponent } from './features/board-letter-matching/board-letter-matching.component';
import { ShapeToColorMatchComponent } from './features/shape-to-color-match/shape-to-color-match.component';
import { SequenceRuleBreakerComponent } from './features/sequence-rule-breaker/sequence-rule-breaker.component';
import { LivingThingsComponent } from './features/living-things/living-things';
import { TrafficSignMatchingComponent } from './features/traffic-sign-matching/traffic-sign-matching.component';
import { AbacusCountingComponent } from './features/abacus-counting/abacus-counting.component';
import { DotPatternDrawingComponent } from './features/dot-pattern-drawing/dot-pattern-drawing.component';
import { FruitCountMatchingComponent } from './features/fruit-count-matching/fruit-count-matching.component';
import { FindMostBallsComponent } from './features/find-most-balls/find-most-balls.component';
import { ShadowMatchingComponent } from './features/shadow-matching/shadow-matching.component';
import { LetterSequenceComponent } from './features/letter-sequence/letter-sequence.component';
import { IdenticalPatternComponent } from './features/identical-pattern/identical-pattern.component';
import { MatchSizeComponent } from './features/match-size/match-size.component';
import { GridColoringComponent } from './features/grid-coloring/grid-coloring.component';
import { FindSameSymbolsComponent } from './features/find-same-symbols/find-same-symbols.component';
import { FindNumbersComponent } from './features/find-numbers/find-numbers.component';
import { FindReversedEComponent } from './features/find-reversed-e/find-reversed-e.component';
import { CountAndAddComponent } from './features/count-and-add/count-and-add.component';
import { RhythmicCountingComponent } from './features/rhythmic-counting/rhythmic-counting.component';
import { TopViewComponent } from './features/top-view/top-view.component';
import { BoxColoringComponent } from './features/box-coloring/box-coloring.component';
import { TriangleSizeComponent } from './features/triangle-size/triangle-size.component';
import { FlowerColoringComponent } from './features/flower-coloring/flower-coloring.component';
import { NotInWordComponent } from './features/not-in-word/not-in-word.component';
import { FindingGreenLinesComponent } from './features/finding-green-lines/finding-green-lines.component';
import { IncorrectNumbersComponent } from './features/incorrect-numbers/incorrect-numbers.component';
import { WaterCapacityComponent } from './features/water-capacity/water-capacity.component';
import { FruitSizeRankingComponent } from './features/fruit-size-ranking/fruit-size-ranking.component';
import { ElderlyPeopleComponent } from './features/elderly-people/elderly-people.component';
import { FindDifferentComponent } from './features/find-different/find-different.component';
import { CylinderSelectionComponent } from './features/cylinder-selection/cylinder-selection.component';
import { PatternCompletionComponent } from './features/pattern-completion/pattern-completion.component';
import { ShapeCountingComponent } from './features/shape-counting/shape-counting.component';
import { HappyChildrenComponent } from './features/happy-children/happy-children.component';
import { DifferentMountainComponent } from './features/different-mountain/different-mountain.component';
import { LetterGridComponent } from './features/letter-grid/letter-grid.component';
import { IceCreamShapeComponent } from './features/ice-cream-shape/ice-cream-shape.component';
import { StartPageComponent } from './features/start-page/start-page.component';
import { EndPageComponent } from './features/end-page/end-page.component';
import { SchoolProfessionComponent } from './features/school-profession/school-profession.component';
import { TallestAnimalComponent } from './features/tallest-animal/tallest-animal.component';
import { ShapeCornersComponent } from './features/shape-corners/shape-corners.component';
import { PencilMatchingV2Component } from './features/pencil-matching-v2/pencil-matching-v2.component';
import { ShapeCountColoringComponent } from './features/shape-count-coloring/shape-count-coloring.component';
import { SportMatchingComponent } from './features/sport-matching/sport-matching.component';
import { LetterCountingComponent } from './features/letter-counting/letter-counting.component';
import { ElephantDirectionComponent } from './features/elephant-direction/elephant-direction.component';
import { SymbolAdditionComponent } from './features/symbol-addition/symbol-addition.component';
import { GridColoringNumbersComponent } from './features/grid-coloring-numbers/grid-coloring-numbers.component';
import { ChildBicycleMatchingComponent } from './features/child-bicycle-matching/child-bicycle-matching.component';
import { SymbolPairMatchingComponent } from './features/symbol-pair-matching/symbol-pair-matching.component';
import { HouseDoorDirectionComponent } from './features/house-door-direction/house-door-direction.component';
import { CountMatchingV2Component } from './features/count-matching-v2/count-matching-v2.component';
import { RectangleSelectionComponent } from './features/rectangle-selection/rectangle-selection.component';
import { CountSixSelectionComponent } from './features/count-six-selection/count-six-selection.component';
import { ElectricApplianceSelectionComponent } from './features/electric-appliance-selection/electric-appliance-selection.component';
import { PatternMatchingThreeComponent } from './features/pattern-matching-three/pattern-matching-three.component';
import { ZebraLetterSelectionComponent } from './features/zebra-letter-selection/zebra-letter-selection.component';
import { ShapeMatchingDrawnComponent } from './features/shape-matching-drawn/shape-matching-drawn.component';
import { WatermelonMathComponent } from './features/watermelon-math/watermelon-math.component';
import { FruitSequenceV2Component } from './features/fruit-sequence-v2/fruit-sequence-v2.component';
import { DoctorSuitabilityComponent } from './features/doctor-suitability/doctor-suitability.component';
import { FruitGroupMatchingComponent } from './features/fruit-group-matching/fruit-group-matching.component';
import { OrangeColoringComponent } from './features/orange-coloring/orange-coloring.component';
import { SymbolGridCountingComponent } from './features/symbol-grid-counting/symbol-grid-counting.component';
import { ObjectCountSelectionComponent } from './features/object-count-selection/object-count-selection.component';
import { FewestTrianglesComponent } from './features/fewest-triangles/fewest-triangles.component';
import { FavoriteActivityComponent } from './features/favorite-activity/favorite-activity.component';
import { CountMatchingV3Component } from './features/count-matching-v3/count-matching-v3.component';
import { EggSubtractionComponent } from './features/egg-subtraction/egg-subtraction.component';
import { HouseItemsComponent } from './features/house-items/house-items.component';
import { PinkGridComponent } from './features/pink-grid/pink-grid.component';
import { LetterCountingV2Component } from './features/letter-counting-v2/letter-counting-v2.component';
import { ShapeCountColoringV2Component } from './features/shape-count-coloring-v2/shape-count-coloring-v2.component';
import { SadExpressionsComponent } from './features/sad-expressions/sad-expressions.component';
import { GeometricSequenceComponent } from './features/geometric-sequence/geometric-sequence.component';
import { FindingRedLinesComponent } from './features/finding-red-lines/finding-red-lines.component';
import { UppercaseLowercaseComponent } from './features/uppercase-lowercase/uppercase-lowercase.component';
import { WordShapeMatchingComponent } from './features/word-shape-matching/word-shape-matching.component';
import { PatternTransferComponent } from './features/pattern-transfer/pattern-transfer.component';
import { LadybugSpotsComponent } from './features/ladybug-spots/ladybug-spots.component';
import { RotateGridComponent } from './features/rotate-grid/rotate-grid.component';
import { ColorByNumberComponent } from './features/color-by-number/color-by-number.component';
import { ToothbrushSelectionComponent } from './features/toothbrush-selection/toothbrush-selection.component';
import { SymbolAdditionV2Component } from './features/symbol-addition-v2/symbol-addition-v2.component';
import { CatSequenceComponent } from './features/cat-sequence/cat-sequence.component';
import { MissingNumberGridComponent } from './features/missing-number-grid/missing-number-grid.component';
import { VegGridTransferComponent } from './features/veg-grid-transfer/veg-grid-transfer.component';
import { SymbolSequencePlacementComponent } from './features/symbol-sequence-placement/symbol-sequence-placement.component';

export const routes: Routes = [
    { path: '', component: StartPageComponent, pathMatch: 'full' },
    { path: 'pattern', component: PatternMatchingComponent },
    { path: 'odd-direction', component: OddDirectionComponent },
    { path: 'shade-sorting', component: ShadeSortingComponent },
    { path: 'number-sequence', component: NumberSequenceComponent },
    { path: 'symbol-matching', component: SymbolMatchingComponent },
    { path: 'multi-condition-selection', component: MultiConditionSelectionComponent },
    { path: 'animal-position', component: AnimalPositionComponent },
    { path: 'pattern-2', component: PatternMatchingTwoComponent },
    { path: 'shape-coloring', component: ShapeColoringComponent },
    { path: 'liquid-selection', component: LiquidSelectionComponent },
    { path: 'longest-rope', component: LongestRopeComponent },
    { path: 'letter-matching', component: LetterMatchingComponent },
    { path: 'shape-pattern', component: ShapePatternComponent },
    { path: 'board-letter-matching', component: BoardLetterMatchingComponent },
    { path: 'shape-to-color-match', component: ShapeToColorMatchComponent },
    { path: 'sequence-rule-breaker', component: SequenceRuleBreakerComponent },
    { path: 'living-things', component: LivingThingsComponent },
    { path: 'traffic-sign-matching', component: TrafficSignMatchingComponent },
    { path: 'abacus-counting', component: AbacusCountingComponent },
    { path: 'dot-pattern-drawing', component: DotPatternDrawingComponent },
    { path: 'fruit-count-matching', component: FruitCountMatchingComponent },
    { path: 'find-most-balls', component: FindMostBallsComponent },
    { path: 'shadow-matching', component: ShadowMatchingComponent },
    { path: 'letter-sequence', component: LetterSequenceComponent },
    { path: 'identical-pattern', component: IdenticalPatternComponent },
    { path: 'match-size', component: MatchSizeComponent },
    { path: 'grid-coloring', component: GridColoringComponent },
    { path: 'find-same-symbols', component: FindSameSymbolsComponent },
    { path: 'find-numbers', component: FindNumbersComponent },
    { path: 'find-reversed-e', component: FindReversedEComponent },
    { path: 'count-and-add', component: CountAndAddComponent },
    { path: 'rhythmic-counting', component: RhythmicCountingComponent },
    { path: 'top-view', component: TopViewComponent },
    { path: 'box-coloring', component: BoxColoringComponent },
    { path: 'triangle-size', component: TriangleSizeComponent },
    { path: 'flower-coloring', component: FlowerColoringComponent },
    { path: 'not-in-word', component: NotInWordComponent },
    { path: 'finding-green-lines', component: FindingGreenLinesComponent },
    { path: 'incorrect-numbers', component: IncorrectNumbersComponent },
    { path: 'water-capacity', component: WaterCapacityComponent },
    { path: 'fruit-size-ranking', component: FruitSizeRankingComponent },
    { path: 'elderly-people', component: ElderlyPeopleComponent },
    { path: 'find-different', component: FindDifferentComponent },
    { path: 'cylinder-selection', component: CylinderSelectionComponent },
    { path: 'pattern-completion', component: PatternCompletionComponent },
    { path: 'shape-counting', component: ShapeCountingComponent },
    { path: 'happy-children', component: HappyChildrenComponent },
    { path: 'different-mountain', component: DifferentMountainComponent },
    { path: 'letter-grid', component: LetterGridComponent },
    { path: 'ice-cream-shape', component: IceCreamShapeComponent },
    { path: 'school-profession', component: SchoolProfessionComponent },
    { path: 'tallest-animal', component: TallestAnimalComponent },
    { path: 'shape-corners', component: ShapeCornersComponent },
    { path: 'pencil-matching-v2', component: PencilMatchingV2Component },
    { path: 'shape-count-coloring', component: ShapeCountColoringComponent },
    { path: 'sport-matching', component: SportMatchingComponent },
    { path: 'letter-counting', component: LetterCountingComponent },
    { path: 'elephant-direction', component: ElephantDirectionComponent },
    { path: 'symbol-addition', component: SymbolAdditionComponent },
    { path: 'grid-coloring-numbers', component: GridColoringNumbersComponent },
    { path: 'child-bicycle-matching', component: ChildBicycleMatchingComponent },
    { path: 'symbol-pair-matching', component: SymbolPairMatchingComponent },
    { path: 'house-door-direction', component: HouseDoorDirectionComponent },
    { path: 'count-matching-v2', component: CountMatchingV2Component },
    { path: 'rectangle-selection', component: RectangleSelectionComponent },
    { path: 'count-six-selection', component: CountSixSelectionComponent },
    { path: 'electric-appliance-selection', component: ElectricApplianceSelectionComponent },
    { path: 'pattern-3', component: PatternMatchingThreeComponent },
    { path: 'zebra-letters', component: ZebraLetterSelectionComponent },
    { path: 'shape-matching-drawn', component: ShapeMatchingDrawnComponent },
    { path: 'watermelon-math', component: WatermelonMathComponent },
    { path: 'fruit-sequence-v2', component: FruitSequenceV2Component },
    { path: 'doctor-suitability', component: DoctorSuitabilityComponent },
    { path: 'fruit-group-matching', component: FruitGroupMatchingComponent },
    { path: 'orange-coloring', component: OrangeColoringComponent },
    { path: 'symbol-grid-counting', component: SymbolGridCountingComponent },
    { path: 'object-count-selection', component: ObjectCountSelectionComponent },
    { path: 'fewest-triangles', component: FewestTrianglesComponent },
    { path: 'favorite-activity', component: FavoriteActivityComponent },
    { path: 'count-matching-v3', component: CountMatchingV3Component },
    { path: 'egg-subtraction', component: EggSubtractionComponent },
    { path: 'house-items', component: HouseItemsComponent },
    { path: 'pink-grid', component: PinkGridComponent },
    { path: 'letter-counting-v2', component: LetterCountingV2Component },
    { path: 'shape-count-coloring-v2', component: ShapeCountColoringV2Component },
    { path: 'sad-expressions', component: SadExpressionsComponent },
    { path: 'geometric-sequence', component: GeometricSequenceComponent },
    { path: 'finding-red-lines', component: FindingRedLinesComponent },
    { path: 'uppercase-lowercase', component: UppercaseLowercaseComponent },
    { path: 'word-shape-matching', component: WordShapeMatchingComponent },
    { path: 'pattern-transfer', component: PatternTransferComponent },
    { path: 'ladybug-spots', component: LadybugSpotsComponent },
    { path: 'rotate-grid', component: RotateGridComponent },
    { path: 'color-by-number', component: ColorByNumberComponent },
    { path: 'toothbrush-selection', component: ToothbrushSelectionComponent },
    { path: 'symbol-addition-v2', component: SymbolAdditionV2Component },
    { path: 'cat-sequence', component: CatSequenceComponent },
    { path: 'missing-number-grid', component: MissingNumberGridComponent },
    { path: 'veg-grid-transfer', component: VegGridTransferComponent },
    { path: 'symbol-sequence-placement', component: SymbolSequencePlacementComponent },
    { path: 'end', component: EndPageComponent },
    { path: '**', redirectTo: '' },
];
