import { Routes } from '@angular/router';
import { PatternMatchingComponent } from './features/pattern-matching/pattern-matching.component';
import { OddDirectionComponent } from './features/odd-direction/odd-direction.component';
import { ShadeSortingComponent } from './features/shade-sorting/shade-sorting.component';
import { NumberSequenceComponent } from './features/number-sequence/number-sequence.component';
import { SymbolMatchingComponent } from './features/symbol-matching/symbol-matching.component';
import { MultiConditionSelectionComponent } from './features/multi-condition-selection/multi-condition-selection.component';
import { AnimalPositionComponent } from './features/animal-position/animal-position.component';
import { PatternMatchingTwoComponent } from './features/pattern-matching-two/pattern-matching-two.component';
import { ShapeColoringComponent } from './features/shape-coloring/shape-coloring.component';
import { LiquidSelectionComponent } from './features/liquid-selection/liquid-selection.component';
import { LongestRopeComponent } from './features/longest-rope/longest-rope.component';
import { LetterMatchingComponent } from './features/letter-matching/letter-matching.component';
import { ShapePatternComponent } from './features/shape-pattern/shape-pattern.component';
import { BoardLetterMatchingComponent } from './features/board-letter-matching/board-letter-matching.component';
import { ShapeToColorMatchComponent } from './features/shape-to-color-match/shape-to-color-match.component';
import { SequenceRuleBreakerComponent } from './features/sequence-rule-breaker/sequence-rule-breaker.component';
import { LivingThingsComponent } from './features/living-things/living-things';
import { TrafficSignMatchingComponent } from './features/traffic-sign-matching/traffic-sign-matching.component';
import { AbacusCountingComponent } from './features/abacus-counting/abacus-counting.component';
import { DotPatternDrawingComponent } from './features/dot-pattern-drawing/dot-pattern-drawing.component';
import { FruitCountMatchingComponent } from './features/fruit-count-matching/fruit-count-matching.component';
import { FindMostBallsComponent } from './features/find-most-balls/find-most-balls.component';
import { ShadowMatchingComponent } from './features/shadow-matching/shadow-matching.component';
import { LetterSequenceComponent } from './features/letter-sequence/letter-sequence.component';
import { IdenticalPatternComponent } from './features/identical-pattern/identical-pattern.component';
import { MatchSizeComponent } from './features/match-size/match-size.component';
import { GridColoringComponent } from './features/grid-coloring/grid-coloring.component';
import { FindSameSymbolsComponent } from './features/find-same-symbols/find-same-symbols.component';
import { FindNumbersComponent } from './features/find-numbers/find-numbers.component';
import { FindReversedEComponent } from './features/find-reversed-e/find-reversed-e.component';
import { CountAndAddComponent } from './features/count-and-add/count-and-add.component';
import { RhythmicCountingComponent } from './features/rhythmic-counting/rhythmic-counting.component';
import { TopViewComponent } from './features/top-view/top-view.component';
import { BoxColoringComponent } from './features/box-coloring/box-coloring.component';
import { TriangleSizeComponent } from './features/triangle-size/triangle-size.component';
import { FlowerColoringComponent } from './features/flower-coloring/flower-coloring.component';
import { NotInWordComponent } from './features/not-in-word/not-in-word.component';
import { FindingGreenLinesComponent } from './features/finding-green-lines/finding-green-lines.component';
import { IncorrectNumbersComponent } from './features/incorrect-numbers/incorrect-numbers.component';

export const routes: Routes = [
    { path: '', redirectTo: 'pattern', pathMatch: 'full' },
    { path: 'pattern', component: PatternMatchingComponent },
    { path: 'odd-direction', component: OddDirectionComponent },
    { path: 'shade-sorting', component: ShadeSortingComponent },
    { path: 'number-sequence', component: NumberSequenceComponent },
    { path: 'symbol-matching', component: SymbolMatchingComponent },
    { path: 'multi-condition-selection', component: MultiConditionSelectionComponent },
    { path: 'animal-position', component: AnimalPositionComponent },
    { path: 'pattern-2', component: PatternMatchingTwoComponent },
    { path: 'shape-coloring', component: ShapeColoringComponent },
    { path: 'liquid-selection', component: LiquidSelectionComponent },
    { path: 'longest-rope', component: LongestRopeComponent },
    { path: 'letter-matching', component: LetterMatchingComponent },
    { path: 'shape-pattern', component: ShapePatternComponent },
    { path: 'board-letter-matching', component: BoardLetterMatchingComponent },
    { path: 'shape-to-color-match', component: ShapeToColorMatchComponent },
    { path: 'sequence-rule-breaker', component: SequenceRuleBreakerComponent },
    { path: 'living-things', component: LivingThingsComponent },
    { path: 'traffic-sign-matching', component: TrafficSignMatchingComponent },
    { path: 'abacus-counting', component: AbacusCountingComponent },
    { path: 'dot-pattern-drawing', component: DotPatternDrawingComponent },
    { path: 'fruit-count-matching', component: FruitCountMatchingComponent },
    { path: 'find-most-balls', component: FindMostBallsComponent },
    { path: 'shadow-matching', component: ShadowMatchingComponent },
    { path: 'letter-sequence', component: LetterSequenceComponent },
    { path: 'identical-pattern', component: IdenticalPatternComponent },
    { path: 'match-size', component: MatchSizeComponent },
    { path: 'grid-coloring', component: GridColoringComponent },
    { path: 'find-same-symbols', component: FindSameSymbolsComponent },
    { path: 'find-numbers', component: FindNumbersComponent },
    { path: 'find-reversed-e', component: FindReversedEComponent },
    { path: 'count-and-add', component: CountAndAddComponent },
    { path: 'rhythmic-counting', component: RhythmicCountingComponent },
    { path: 'top-view', component: TopViewComponent },
    { path: 'box-coloring', component: BoxColoringComponent },
    { path: 'triangle-size', component: TriangleSizeComponent },
    { path: 'flower-coloring', component: FlowerColoringComponent },
    { path: 'not-in-word', component: NotInWordComponent },
    { path: 'finding-green-lines', component: FindingGreenLinesComponent },
    { path: 'incorrect-numbers', component: IncorrectNumbersComponent },
    { path: '**', redirectTo: 'pattern' },
];
